version: "3"

services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis

  img:
    build: img
    env_file: img/.env.sample
    environment:
      - DATABASE_URL=postgres://postgres@postgres/picture_development
    command: yarn start
    volumes:
      - ./img:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  web:
    build: web
    env_file: web/.env.sample
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - REDIS_URL=redis://redis:6379/1
    command: bundle exec rails server -p 3000 -b "0.0.0.0"
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - img

volumes:
  postgres:
